### ISSUE TITLE
CircleCI環境を構築する

### ISSUE THREAD

**Issue by h5y1m141** [h5y1m141/urban_outdoor#53]
issue #51 の対応が完了したら行う
- [ ] pendingなspecがいくつかあるのでひとまず削除する
- [ ] circle.mlを以下内容で作成する

``` yaml
machine:
  timezone:
    Asia/Tokyo
test:
  pre:
    - bundle exec rspec spec
    - bundle exec teaspoon
```
