### ISSUE TITLE
Vagrant環境のCentOSのMariaDBの起動設定

### ISSUE THREAD

**Issue by h5y1m141** [h5y1m141/urban_outdoor#71]
Ansibleのレシピを追加する
- [ ] 以下の様な感じで起動設定

``` yml

---
- name: start MySQL
  shell: service mysqld start
  tags: mysqld
```
- [ ] 上記が問題なかったら、MySQLの初期設定
